<?php
/**
 * @category    M2Commerce Enterprise
 * @package     M2Commerce_OrderComment
 * @copyright   Copyright (c) 2025 M2Commerce Enterprise
 * @author      dawoodgondaldev@gmail.com
 */

use Magento\Framework\Escaper;
use M2Commerce\YoutubeWidget\Block\Widget\Youtube;

/** @var Youtube $block */
/** @var Escaper $escaper */

$videoUrl = $block->getVideoId();
$title = $block->getVideoTitle();
$width = $block->getWidth();
$height = $block->getHeight();
$autoplay = $block->isAutoplay();
?>

<?php if ($videoUrl): ?>
    <div class="youtube-widget" style="text-align:center;">
        <h2><?= $escaper->escapeHtmlAttr($title) ?></h2>
        <iframe width="<?= $escaper->escapeHtmlAttr($width) ?>"
                height="<?= $escaper->escapeHtmlAttr($height) ?>"
                src="https://www.youtube.com/embed/<?= $escaper->escapeHtmlAttr($videoUrl) ?>?autoplay=<?= $escaper->escapeHtmlAttr($autoplay) ?>"
                title="<?= $escaper->escapeHtmlAttr($title) ?>"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
        </iframe>
    </div>
<?php endif; ?>
